object Versions {
    const val buildGradle = "4.2.0-beta06"
    const val kotlin = "1.4.32"
    const val coreKtx = "1.3.2"
    const val appCompat = "1.2.0"
    const val material = "1.3.0"
    const val constraintLayout = "2.0.4"
    const val navigation = "2.3.4"
    const val lifecycleLiveData = "2.3.1"
    const val groupie = "2.9.0"
    const val coil = "1.1.1"
    const val moshi = "1.9.3"
    const val daggerHilt = "2.33-beta"
    const val androidXHilt = "1.0.0-alpha01"
}

object Libs {
    const val buildGradle = "com.android.tools.build:gradle:${Versions.buildGradle}"
    const val kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val navigationUI = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val lifecycleLiveData = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycleLiveData}"
    const val groupie = "com.xwray:groupie:${Versions.groupie}"
    const val groupieViewBinding = "com.xwray:groupie-viewbinding:${Versions.groupie}"
    const val coil = "io.coil-kt:coil:${Versions.coil}"
    const val moshi = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    const val daggerHilt = "com.google.dagger:hilt-android:${Versions.daggerHilt}"
    const val daggerHiltCompiler = "com.google.dagger:hilt-android-compiler:${Versions.daggerHilt}"
    const val daggerHiltGradlePlugin = "com.google.dagger:hilt-android-gradle-plugin:${Versions.daggerHilt}"
    const val hiltLifecycleViewModel = "androidx.hilt:hilt-lifecycle-viewmodel:${Versions.androidXHilt}"
    const val hiltCompiler = "androidx.hilt:hilt-compiler:${Versions.androidXHilt}"
}